### PR TITLE
- Update to Latest Version

### PR DESCRIPTION
**Pull request by milansurelia**
- Null-Safety Migration
- Updated dependencies
- Updated SDK Version

This PR will also resolve [this issue](https://github.com/wsloth/Index/issues/18).

### CODE REVIEW

**Comment by milansurelia** [comment]
@wsloth I have updated the SDK Version in `pubspec.yaml`. I think you need to update the flutter version in github workflow file, or else it will get failed every time.

**Comment by wsloth** [comment]
Hi @milansurelia -- sorry for the late response! Could you update the github workflow file as well in your PR to reflect these changes? It should theoretically just be changing the flutter SDK version. If you're not able to because of PR policies, I'll merge this breaking version and update the file in a separate PR. 

Thanks for your amazing contribution by the way!!! Really happy with this 😄 🎊

**Comment by milansurelia** [comment]
> Hi @milansurelia -- sorry for the late response! Could you update the github workflow file as well in your PR to reflect these changes? It should theoretically just be changing the flutter SDK version. If you're not able to because of PR policies, I'll merge this breaking version and update the file in a separate PR.
> 
> Thanks for your amazing contribution by the way!!! Really happy with this 😄 🎊

@wsloth Thank you!
I will create a new PR that will contain the changes for the workflow update.

**Comment by wsloth** [comment]
Merging anyway, fixing build in another PR

**Pull request merged**
