### PR TITLE
Implemented Onboarding Screen.

### PR DESCRIPTION
**Pull request by ShivamMenda**
Added Onboarding screen with graphics.

### CODE REVIEW

**Comment by wsloth** [comment]
Thanks for your contribution @ShivamMenda! I'm currently not able to review the changes in the app because I don't have my right computer with me, but I will check it out later tonight. In any case, this PR is definitely `hacktoberfest-accepted`! 👏 

I'll keep you updated on the merge progress.

**Comment by wsloth** [comment]
Thanks for taking a look @ShivamMenda! And let me know if you're unable to figure it out, in which case I'll create a separate issue request for it :)

**Comment by ShivamMenda** [comment]
@wsloth yeah I'll keep you updated. Is it fine if I take a day to research and get back to you?

**Comment by ShivamMenda** [comment]
@wsloth Sure will get back to you.Thanks.

**Comment by ShivamMenda** [comment]
@wsloth any update on the merge?

**Pull request merged**
